---
file: /var/log/nginx/access.log
sort: count
limit: 20000
reverse: true
percentiles: [50, 90, 99]
output: count,1xx,2xx,3xx,4xx,5xx,method,uri,sum,avg,max,min,p50,p90,p99,sum_body,avg_body,max_body,min_body
ltsv: {}
json: {}
regexp: {}

matching_groups:
  - '/api/user/[^/]/theme'
  - '/api/user/[^/]/livestream'
  - '/api/livestream/[^/]'
  - '/api/livestream/[^/]/livecomment'
  - '/api/livestream/[^/]/reaction'
  - '/api/livestream/[^/]/report'
  - '/api/livestream/[^/]/ngwords'
  - '/api/livestream/[^/]/livecomment/[^/]/report'
  - '/api/livestream/[^/]/moderate'
  - '/api/livestream/[^/]/enter'
  - '/api/livestream/[^/]/exit'
  - '/api/user/[^/]'
  - '/api/user/[^/]/statistics'
  - '/api/user/[^/]/icon'
  - '/api/livestream/[^/]/statistics'